from .icons import (
    svg,
    ICO_FILE, ICO_PULSE, ICO_GRID, ICO_MODEL, ICO_SETTINGS, ICO_USER,
    ICO_INFO, ICO_FOLDER, ICO_REFRESH, ICO_PLAY, ICO_STOP, ICO_CLOCK,
    ICO_TERM, ICO_DL, ICO_LOGOUT, ICO_LOGIN, ICO_SUN, ICO_MOON,
    ICO_CHECK, ICO_WARN, ICO_SEARCH, ICO_CHEVRON, ICO_KEY, ICO_SHIELD, ICO_PALETTE,
)
from .shell import shell_layout, sidebar
